[package]
edition = "2021"
name = "pruntime"
version = "0.1.0"

[profile.release]
panic = "abort"

[dependencies]
log = "0.4.14"
rocket = "0.4.7"

env_logger = {version = "0.9.0", default-features = false, features = ["termcolor"]}

[patch.crates-io]
hyper = { path = "hyper-0.10.16" }
